#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

REDISPORT="${2-26589}"
REDISHOME=/oss/redis
EXEC=$REDISHOME/bin/redis-sentinel
CLIEXEC=$REDISHOME/bin/redis-cli

PIDFILE=$REDISHOME/tmp/sentinel-${REDISPORT}.pid
CONF=$REDISHOME/conf/sentinel-${REDISPORT}.conf

usage () {
        basename=`basename "$0"`
        echo "USAGE: $basename {start|stop|status|restart} [port<default:$REDISPORT>]"
        echo " e.g.: $basename start $REDISPORT"
        echo "       $basename status $REDISPORT"
        echo "       $basename stop $REDISPORT"
}

stats () {
        echo "=========================================="
        $CLIEXEC -p $REDISPORT info Sentinel
        echo "=========================================="
}

case "$1" in
    start)
        $EXEC $CONF
        ;;
    stop)
        echo "Stopping ..."
        $CLIEXEC -p $REDISPORT shutdown save
        ;;
    status)
        stats
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        usage
        ;;
esac
